# Setup
title:        CUE4CHNG
tagline:      Curriculum Undergraduate Education
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Rafael Ferreira da Silva
  url:        http://rafaelsilva.com

#Others
markdown: kramdown